dist: xenial
language: go

go:
- 1.x
- "1.10"
- 1.11.x
- master

before_install:
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

before_script:
    - sleep 15
    - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
    - go test ./tests -v
    - $GOPATH/bin/goveralls -service=travis-ci

services:
    - mongodb
    - memcached